export const FETCH_DOCUMENT = 'FETCH_DOCUMENT'

export const FETCH_DOCUMENTMESSAGES = 'FETCH_DOCUMENTMESSAGES'

export const RECEIVE_DOCUMENTMESSAGES = 'RECEIVE_DOCUMENTMESSAGES'

export const REMOVED_DOCUMENT = 'REMOVED_DOCUMENT'

export const RECEIVE_REMOVEDDOCUMENT = 'RECEIVE_REMOVEDDOCUMENT'

export const RECOVER_DOCUMENT = 'RECOVER_DOCUMENT'

export const ADD_DOCUMENT = 'ADD_DOCUMENT'

export const RECEIVE_DOCUMENT = 'RECEIVE_DOCUMENT'

export const ERROR_DOCUMENT = 'ERROR_DOCUMENT'

export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT'

export const UPDATE_LOCALDOCUMENT = 'UPDATE_LOCALDOCUMENT'

export const REMOVE_DOCUMENT = 'REMOVE_DOCUMENT'

export const REMOVE_LOCALDOCUMENT = 'REMOVE_LOCALDOCUMENT'

export const NOTHING = 'NOTHING'