export const FETCHBASE_MODEL = 'FETCHBASE_MODEL'

export const FETCHCUSTOM_MODEL = 'FETCHCUSTOM_MODEL'

export const ADD_MODEL = 'ADD_MODEL'

export const RECEIVEBASE_MODEL = 'RECEIVEBASE_MODEL'

export const RECEIVECUSTOM_MODEL = 'RECEIVECUSTOM_MODEL'

export const ERROR_MODEL = 'ERROR_MODEL'

export const UPDATE_MODEL = 'UPDATE_MODEL'

export const UPDATE_LOCALMODEL = 'UPDATE_LOCALMODEL'

export const REMOVE_MODEL = 'REMOVE_MODEL'

export const REMOVE_LOCALMODEL = 'REMOVE_LOCALMODEL'

export const NOTHING = 'NOTHING'
