export const FETCH_PROJECT = 'FETCH_PROJECT'

export const ADD_PROJECT = 'ADD_PROJECT'

export const ALL_PROJECT = 'ALL_PROJECT'

export const REMOVED_INTERFACE = 'REMOVED_INTERFACE'

export const RECEIVE_REMOVEDINTERFACE = 'RECEIVE_REMOVEDINTERFACE'

export const RECOVER_INTERFACE = 'RECOVER_INTERFACE'

export const REMOVED_PROJECT = 'REMOVED_PROJECT'

export const RECEIVE_REMOVEDPROJECT = 'RECEIVE_REMOVEDPROJECT'

export const RECOVER_PROJECT = 'RECOVER_PROJECT'

export const RECEIVE_ALLPROJECT = 'RECEIVE_ALLPROJECT'

export const UPDATE_PROJECT = 'UPDATE_PROJECT'

export const UPDATE_LOCALPROJECT = 'UPDATE_LOCALPROJECT'

export const REMOVE_PROJECT = 'REMOVE_PROJECT'

export const REMOVE_LOCALPROJECT = 'REMOVE_LOCALPROJECT'

export const IMPORT_PROJECT = 'IMPORT_PROJECT'

export const CLONE_PROJECT = 'CLONE_PROJECT'

export const CLONE_INTERFACE = 'CLONE_INTERFACE'

export const VERIFY_PROJECT = 'VERIFY_PROJECT'

export const RECEIVE_VERIFYPROJECT = 'RECEIVE_VERIFYPROJECT'

export const RECEIVE_PROJECT = 'RECEIVE_PROJECT'

export const ERROR_PROJECT = 'ERROR_PROJECT'

export const FETCH_UNJOINPROJECT = 'FETCH_UNJOINPROJECT'

export const RECEIVE_UNJOINPROJECT = 'RECEIVE_UNJOINPROJECT'

export const FETCH_DEMO = 'FETCH_DEMO'

export const RECEIVE_DEMO = 'RECEIVE_DEMO'

export const NOTHING = 'NOTHING'

export const ADD_INTERFACE = 'ADD_INTERFACE'

export const UPDATE_INTERFACE = 'UPDATE_INTERFACE'

export const UPDATE_LOCALINTERFACE = 'UPDATE_LOCALINTERFACE'

export const REMOVE_INTERFACE = 'REMOVE_INTERFACE'

export const REMOVE_LOCALINTERFACE = 'REMOVE_LOCALINTERFACE'