export const FETCH_PROJECT = 'FETCH_PROJECT'
export const ADD_PROJECT = 'ADD_PROJECT'

export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const UPDATE_LOCALPROJECT = 'UPDATE_LOCALPROJECT'
export const REMOVE_PROJECT = 'REMOVE_PROJECT'
export const REMOVE_LOCALPROJECT = 'REMOVE_LOCALPROJECT'
export const IMPORT_PROJECT = 'IMPORT_PROJECT'
export const CLONE_PROJECT = 'CLONE_PROJECT'

export const RECEIVE_PROJECT = 'RECEIVE_PROJECT'
export const ERROR_PROJECT = 'ERROR_PROJECT'
export const FETCH_UNJOINPROJECT = 'FETCH_UNJOINPROJECT'
export const RECEIVE_UNJOINPROJECT = 'RECEIVE_UNJOINPROJECT'

export const FETCH_DEMO = 'FETCH_DEMO'
export const RECEIVE_DEMO = 'RECEIVE_DEMO'
export const NOTHING = 'NOTHING'